"""Render :class:`AppConfig` into a Compose ``.env`` file.

The output is a ``KEY=VALUE`` dotenv document consumed via ``env_file``.
It carries the strategy / FreqAI command arguments (``FREQTRADE_ARGS``)
and the runtime secrets, so it is git-ignored and must never be committed.
"""

from __future__ import annotations

from common.contracts import AppConfig
from ftctl.render.freqtrade import freqtrade_args, freqtrade_tag


def _quote(value: str) -> str:
    """Double-quote a dotenv value when it contains spaces or special chars."""
    if any(ch in value for ch in (" ", "#", '"', "'")):
        return '"' + value.replace('"', '\\"') + '"'
    return value


def render_compose(cfg: AppConfig, source: str = "config/app.yaml") -> str:
    """Build the Compose env-file text for the given app config."""
    dry_run = cfg.mode == "dry_run"
    lines = [
        f"# Generated by ftctl from {source} — do not edit or commit.",
        "# Contains secrets; this file is git-ignored (*.generated.*).",
        f"FT_MODE={cfg.mode}",
        f"FT_DRY_RUN={'true' if dry_run else 'false'}",
        f"FT_EXCHANGE={_quote(cfg.exchange.name)}",
        f"FT_PAIRS={_quote(' '.join(cfg.exchange.pairs))}",
        f"FT_STAKE_CURRENCY={_quote(cfg.exchange.stake_currency)}",
        f"FT_STAKE_AMOUNT={cfg.exchange.stake_amount}",
        f"FT_MAX_STAKE={cfg.exchange.max_stake}",
        f"FT_STRATEGY={_quote(cfg.strategy.name)}",
        f"FT_TIMEFRAME={_quote(cfg.strategy.timeframe)}",
        f"FT_FREQAI_ENABLED={'true' if cfg.freqai.enabled else 'false'}",
        f"FT_FREQAIMODEL={_quote(cfg.freqai.model)}",
        f"FREQTRADE_TAG={freqtrade_tag(cfg)}",
        f"FREQTRADE_ARGS={_quote(' '.join(freqtrade_args(cfg)))}",
        f"INFERENCE_URL={_quote(cfg.inference.url)}",
        f"INFERENCE_DEFAULT_MODEL={_quote(cfg.inference.default_model)}",
        f"BINANCE_API_KEY={_quote(cfg.secrets.binance_key)}",
        f"BINANCE_API_SECRET={_quote(cfg.secrets.binance_secret)}",
        f"FT_API_USERNAME={_quote(cfg.secrets.ft_api_username)}",
        f"FT_API_PASSWORD={_quote(cfg.secrets.ft_api_password)}",
    ]
    return "\n".join(lines) + "\n"
